ALTER TABLE experimentdata
ADD COLUMN cn_1_1 SMALLINT,
ADD COLUMN cn_1_2 SMALLINT,
ADD COLUMN cn_1_3 SMALLINT,
ADD COLUMN cn_2_1 SMALLINT,
ADD COLUMN cn_2_2 SMALLINT,
ADD COLUMN cn_2_3 SMALLINT,
ADD COLUMN en_1_1 SMALLINT,
ADD COLUMN en_1_2 SMALLINT,
ADD COLUMN en_1_3 SMALLINT,
ADD COLUMN se_1_1 SMALLINT,
ADD COLUMN se_1_2 SMALLINT,
ADD COLUMN se_1_3 SMALLINT;