ALTER TABLE experimentdata
ADD COLUMN eval_1_1 SMALLINT,
ADD COLUMN eval_1_2 SMALLINT,
ADD COLUMN eval_1_3 SMALLINT,
ADD COLUMN eval_2_1 SMALLINT,
ADD COLUMN eval_2_2 SMALLINT,
ADD COLUMN eval_2_3 SMALLINT,
ADD COLUMN eval_3_1 SMALLINT,
ADD COLUMN eval_3_2 SMALLINT,
ADD COLUMN eval_3_3 SMALLINT;