from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

# db.BigInteger
# db.SmallInteger
# db.Boolean

class ExperimentData(db.Model):
    __tablename__ = 'experimentdata'

    # Metadata Columns
    id = db.Column(db.Integer, primary_key=True)
    time_start = db.Column(db.BigInteger)
    time_finish = db.Column(db.BigInteger)
    task1_start = db.Column(db.BigInteger)
    task1_finish = db.Column(db.BigInteger)
    task2_start = db.Column(db.BigInteger)
    task2_finish = db.Column(db.BigInteger)
    task3_start = db.Column(db.BigInteger)
    task3_finish = db.Column(db.BigInteger)
    condition_id = db.Column(db.SmallInteger)
    first_task = db.Column(db.SmallInteger)
    second_task = db.Column(db.SmallInteger)
    third_task = db.Column(db.SmallInteger)
    first_algorithm = db.Column(db.SmallInteger)
    second_algorithm = db.Column(db.SmallInteger)
    third_algorithm = db.Column(db.SmallInteger)

    # Demographic Questionnaire Columns
    age = db.Column(db.SmallInteger)
    gender = db.Column(db.String(20))
    nationality = db.Column(db.String(80))
    experience = db.Column(db.SmallInteger)
    consumption = db.Column(db.Integer)

    # Task Data Columns
    task1_movie = db.Column(db.Boolean)
    task1_series = db.Column(db.Boolean)
    task1_search = db.Column(db.Boolean)
    task2_movie = db.Column(db.Boolean)
    task2_series = db.Column(db.Boolean)
    task2_search = db.Column(db.Boolean)
    task3_movie = db.Column(db.Boolean)
    task3_series = db.Column(db.Boolean)
    task3_search = db.Column(db.Boolean)

    # Algorithm Data Columns
    algorithm1_movie = db.Column(db.Boolean)
    algorithm1_series = db.Column(db.Boolean)
    algorithm1_search = db.Column(db.Boolean)
    algorithm2_movie = db.Column(db.Boolean)
    algorithm2_series = db.Column(db.Boolean)
    algorithm2_search = db.Column(db.Boolean)
    algorithm3_movie = db.Column(db.Boolean)
    algorithm3_series = db.Column(db.Boolean)
    algorithm3_search = db.Column(db.Boolean)

    # Gratification Questionnaire Columns
    grat_1_1 = db.Column(db.SmallInteger)
    grat_2_1 = db.Column(db.SmallInteger)
    grat_3_1 = db.Column(db.SmallInteger)
    grat_4_1 = db.Column(db.SmallInteger)
    grat_5_1 = db.Column(db.SmallInteger)
    grat_6_1 = db.Column(db.SmallInteger)
    grat_7_1 = db.Column(db.SmallInteger)
    grat_8_1 = db.Column(db.SmallInteger)
    grat_9_1 = db.Column(db.SmallInteger)
    grat_10_1 = db.Column(db.SmallInteger)
    grat_11_1 = db.Column(db.SmallInteger)
    grat_12_1 = db.Column(db.SmallInteger)
    grat_13_1 = db.Column(db.SmallInteger)
    grat_1_2 = db.Column(db.SmallInteger)
    grat_2_2 = db.Column(db.SmallInteger)
    grat_3_2 = db.Column(db.SmallInteger)
    grat_4_2 = db.Column(db.SmallInteger)
    grat_5_2 = db.Column(db.SmallInteger)
    grat_6_2 = db.Column(db.SmallInteger)
    grat_7_2 = db.Column(db.SmallInteger)
    grat_8_2 = db.Column(db.SmallInteger)
    grat_9_2 = db.Column(db.SmallInteger)
    grat_10_2 = db.Column(db.SmallInteger)
    grat_11_2 = db.Column(db.SmallInteger)
    grat_12_2 = db.Column(db.SmallInteger)
    grat_13_2 = db.Column(db.SmallInteger)
    grat_1_3 = db.Column(db.SmallInteger)
    grat_2_3 = db.Column(db.SmallInteger)
    grat_3_3 = db.Column(db.SmallInteger)
    grat_4_3 = db.Column(db.SmallInteger)
    grat_5_3 = db.Column(db.SmallInteger)
    grat_6_3 = db.Column(db.SmallInteger)
    grat_7_3 = db.Column(db.SmallInteger)
    grat_8_3 = db.Column(db.SmallInteger)
    grat_9_3 = db.Column(db.SmallInteger)
    grat_10_3 = db.Column(db.SmallInteger)
    grat_11_3 = db.Column(db.SmallInteger)
    grat_12_3 = db.Column(db.SmallInteger)
    grat_13_3 = db.Column(db.SmallInteger)

    # Evaluation Questionnaire Columns
    eval_1_1 = db.Column(db.SmallInteger)
    eval_2_1 = db.Column(db.SmallInteger)
    eval_3_1 = db.Column(db.SmallInteger)
    eval_4_1 = db.Column(db.SmallInteger)
    eval_5_1 = db.Column(db.SmallInteger)
    eval_6_1 = db.Column(db.SmallInteger)
    eval_7_1 = db.Column(db.SmallInteger)
    eval_8_1 = db.Column(db.SmallInteger)
    eval_9_1 = db.Column(db.SmallInteger)
    eval_10_1 = db.Column(db.SmallInteger)
    eval_1_2 = db.Column(db.SmallInteger)
    eval_2_2 = db.Column(db.SmallInteger)
    eval_3_2 = db.Column(db.SmallInteger)
    eval_4_2 = db.Column(db.SmallInteger)
    eval_5_2 = db.Column(db.SmallInteger)
    eval_6_2 = db.Column(db.SmallInteger)
    eval_7_2 = db.Column(db.SmallInteger)
    eval_8_2 = db.Column(db.SmallInteger)
    eval_9_2 = db.Column(db.SmallInteger)
    eval_10_2 = db.Column(db.SmallInteger)
    eval_1_3 = db.Column(db.SmallInteger)
    eval_2_3 = db.Column(db.SmallInteger)
    eval_3_3 = db.Column(db.SmallInteger)
    eval_4_3 = db.Column(db.SmallInteger)
    eval_5_3 = db.Column(db.SmallInteger)
    eval_6_3 = db.Column(db.SmallInteger)
    eval_7_3 = db.Column(db.SmallInteger)
    eval_8_3 = db.Column(db.SmallInteger)
    eval_9_3 = db.Column(db.SmallInteger)
    eval_10_3 = db.Column(db.SmallInteger)

    # Comments Column
    feedback = db.Column(db.String(800))